# Generated by Django 3.1.4 on 2021-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload/flashcard/')),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('word_type', models.CharField(max_length=255, null=True)),
                ('phon_uk', models.CharField(max_length=255, null=True)),
                ('phon_us', models.CharField(max_length=255, null=True)),
                ('sound_uk', models.FileField(blank=True, upload_to='audio/')),
                ('sound_us', models.FileField(blank=True, upload_to='audio/')),
                ('meaning', models.CharField(max_length=255, null=True)),
                ('definition', models.TextField(null=True)),
                ('example', models.TextField(null=True)),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(blank=True, null=True, to='flashcard.Topic')),
            ],
        ),
    ]
