# Generated by Django 3.1.4 on 2021-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularycard',
            name='sound',
            field=models.FileField(blank=True, default=1, upload_to='upload/flashcard/audio/'),
            preserve_default=False,
        ),
    ]
