# Generated by Django 3.1.4 on 2021-03-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20210326_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularycard',
            old_name='phon',
            new_name='phon_uk',
        ),
        migrations.RenameField(
            model_name='vocabularycard',
            old_name='sound',
            new_name='sound_uk',
        ),
        migrations.AddField(
            model_name='vocabularycard',
            name='phon_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocabularycard',
            name='sound_us',
            field=models.FileField(blank=True, upload_to='upload/flashcard/audio/'),
        ),
        migrations.AlterField(
            model_name='vocabularycard',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='flashcard.Topic'),
        ),
    ]
