# Generated by Django 3.1.4 on 2021-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_auto_20210326_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularycard',
            name='sound_uk',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='vocabularycard',
            name='sound_us',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
